# Computation on NumPy Arrays

######  Computation on NumPy arrays can be very fast, or it can be very slow
###### the key to making it fast is to use vectorized operations

In [1]:
import numpy as np
np.random.seed(0)

def compute_reciprocals(values):
    output = np.empty(len(values))
    for i in range(len(values)):
        output[i] = 1.0/values[i]
    return output
values = np.random.randint(1,10,size=5)
compute_reciprocals(values)

array([0.16666667, 1.        , 0.25      , 0.25      , 0.125     ])

In [2]:
big_array = np.random.randint(1,100,size=1000000)
%time compute_reciprocals(big_array)

Wall time: 1.54 s


array([0.1       , 0.01190476, 0.04545455, ..., 0.01428571, 0.01098901,
       0.01149425])

## Introducing UFuncs

In [3]:
print(compute_reciprocals(values))
print(1.0/values)

[0.16666667 1.         0.25       0.25       0.125     ]
[0.16666667 1.         0.25       0.25       0.125     ]


In [4]:
%timeit (1.0/big_array)

3.93 ms ± 42 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [5]:
np.arange(5)/np.arange(1,6)

array([0.        , 0.5       , 0.66666667, 0.75      , 0.8       ])

In [6]:
x = np.arange(9).reshape((3,3))
2**x

array([[  1,   2,   4],
       [  8,  16,  32],
       [ 64, 128, 256]], dtype=int32)

### Exploring Numpy's UFuncs

###### Array arithmetic

In [7]:
x = np.arange(4)
print("x     =",x)
print("x + 5=",x+5)
print("x - 5=", x-5)
print("x*2 =",x*2)
print("x/2 =", x/2)
print("x//2 =", x//2)

x     = [0 1 2 3]
x + 5= [5 6 7 8]
x - 5= [-5 -4 -3 -2]
x*2 = [0 2 4 6]
x/2 = [0.  0.5 1.  1.5]
x//2 = [0 0 1 1]


In [8]:
print("-x     =",-x)
print("x**2 =",x**2)
print("x%2 =",x%2)

-x     = [ 0 -1 -2 -3]
x**2 = [0 1 4 9]
x%2 = [0 1 0 1]


In [9]:
-(.5*x + 1) **2

array([-1.  , -2.25, -4.  , -6.25])

In [10]:
np.add(x,2)

array([2, 3, 4, 5])

###### Absolute value

In [13]:
x = np.array([-2,-1,0,1,2])
abs(x)

array([2, 1, 0, 1, 2])

In [14]:
np.absolute(x)

array([2, 1, 0, 1, 2])

In [15]:
np.abs(x)

array([2, 1, 0, 1, 2])

In [19]:
x = np.array([3-4j,4-3j,2+0j,0+1j])
np.abs(x)

array([5., 5., 2., 1.])

In [20]:
x[0].dtype()

TypeError: 'numpy.dtype' object is not callable

In [21]:
np.dtype(x[0])

dtype('complex128')