# A python List is More Than Just a List


In [1]:
L = list(range(10))
L

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [2]:
type(L[0])

int

#### List of strings

In [3]:
L2 = [str(c) for c in L]
L2

['0', '1', '2', '3', '4', '5', '6', '7', '8', '9']

In [4]:
type(L2[0])

str

#### Because of python's dynamic typing, we can also create heterogeneous lists 

In [5]:
L3 = [True,"2",3.0,4]
[type(item) for item in L3]

[bool, str, float, int]

## Fixed-Type Arrays in Python

In [6]:
import array
L = list(range(10))
A = array.array('i', L)
A

array('i', [0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

###### 'i' is a type code for indicating the contents are integers

## Creating Arrays from Python Lists

In [7]:
import numpy as np

In [8]:
np.array([1,4,2,5,3])

array([1, 4, 2, 5, 3])

###### Unlike python lists, numpy is constrained to arrays that all contain same types. If the types donot match, numpy will upcast if possible(here the integers are upcast to floating point)

In [9]:
np.array([3.14,4,2,3])

array([3.14, 4.  , 2.  , 3.  ])

###### if we want we can explicitly set data type of the resulting array using dtype keyword

In [10]:
np.array([1,2,3,4], dtype='float32')

array([1., 2., 3., 4.], dtype=float32)

In [11]:
# nested lists result in multidimentional arrays
np.array([range(i, i+3) for i in [2,4,6]])

array([[2, 3, 4],
       [4, 5, 6],
       [6, 7, 8]])

### Creating arrays from scratch

In [12]:
# Create a length-10 integer array filled with zeros
np.zeros(10, dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [13]:
#create a 3x5 floating-point array filled with 1s
np.ones((3,5),dtype=float)

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [14]:
#Create a 3x5 array filled with 3.14
np.full((3,5), 3.14)

array([[3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14]])

In [15]:
#Create an arrya filled with linear sequence 
#Starting at 0, ending at 20, stepping 2
# (This is similar to the built in range() function)
np.arange(0,20,2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [16]:
#create an array of five values evenly spaced between 0 and 1
np.linspace(0,1,5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [19]:
#create a 3x3 arrah of uniformly distributed 
#random values between 0 and 1
np.random.random((3,3))

array([[0.57012272, 0.74738859, 0.50596644],
       [0.78751853, 0.59400136, 0.74836797],
       [0.26684603, 0.25793219, 0.80679993]])

In [20]:
# create a 3x3 array of normally distributed random values 
#with mean 0 and standard deviation 1
np.random.normal(0,1,(3,3))

array([[-9.90759156e-01, -2.78787738e-01,  1.51679964e+00],
       [ 9.47953105e-01,  3.10210982e-01,  7.52132108e-01],
       [-2.14310258e-04, -2.16715177e-01,  1.20191411e+00]])

In [22]:
#create a 3x3 array of random integers in the intervarl of[0,10]
np.random.randint(0,10,(3,3))

array([[3, 3, 5],
       [4, 5, 3],
       [1, 2, 5]])

In [23]:
#create a 3x3 identity matrix
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [24]:
#create an uninitiated array of three integers 
# The values will be whatever happens to alraeady exist at that 
# memory location
np.empty(3)

array([1., 1., 1.])